[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
anchor_program = "96MN7K4ArcwdguXMUmVphVaapp5xFyLzpKTrD8dKohGF"

[programs.devnet]
anchor_program = "5M5gc4khWwyba2iz9bAmUV2j9SaG5ki1BFvV1tsnoEQg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"

[test.validator]
url = "https://api.devnet.solana.com"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false